# deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sagan-deployment
  namespace: default
  labels:
    app: sagan-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sagan-app
  template:
    metadata:
      labels:
        app: sagan-app
    spec:
      containers:
      - name: sagan-container
        image: us-central1-docker.pkg.dev/sagan-5/sagan-image-repo/sagan-image:test
        ports:
        - containerPort: 8000 
        readinessProbe:
          httpGet:
            path: /healthz 
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10





