# HTTP-to-HTTPS redirection for GKE
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: https-redirect-config
  namespace: default
spec:
  redirectToHttps:
    enabled: true
    # Optional: Specifies the redirect response code (Default: 301)
    responseCodeName: MOVED_PERMANENTLY_DEFAULT 

